___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# Missing Data

Let's show a few convenient methods to deal with Missing Data in pandas:

In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

In [ ]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [ ]:
df.dropna() ## By default it check for rows

     A    B  C
0  1.0  5.0  1

In [ ]:
df.dropna(axis=1) ## Here, its gonna check for columns

   C
0  1
1  2
2  3

In [5]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [6]:
df.dropna(thresh=2)  ## keep only those rows with atleast 2 nan values which means the cuttoff for checking nan values is 2

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [7]:
df.dropna(thresh=3)

     A    B  C
0  1.0  5.0  1

In [8]:
df.dropna(thresh=1)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [ ]:
df.fillna(value='FILL VALUE')

            A           B  C
0           1           5  1
1           2  FILL VALUE  2
2  FILL VALUE  FILL VALUE  3

In [11]:
df.fillna(value='0', inplace=True)

In [12]:
df

     A    B  C
0  1.0  5.0  1
1  2.0    0  2
2    0    0  3

In [ ]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [15]:
df["C"].mean()

2.0

# Great Job!